{"name": "Тест на ввод данных и клик на кнопку \"Восстановить\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5d95bcadec7a <unknown>\n#1 0x5d95bc7c1e2c <unknown>\n#2 0x5d95bc80e661 <unknown>\n#3 0x5d95bc80e751 <unknown>\n#4 0x5d95bc852f64 <unknown>\n#5 0x5d95bc8315ed <unknown>\n#6 0x5d95bc850303 <unknown>\n#7 0x5d95bc831363 <unknown>\n#8 0x5d95bc801247 <unknown>\n#9 0x5d95bc801b9e <unknown>\n#10 0x5d95bcaa524b <unknown>\n#11 0x5d95bcaa92f1 <unknown>\n#12 0x5d95bca90afe <unknown>\n#13 0x5d95bcaa9e52 <unknown>\n#14 0x5d95bca7579f <unknown>\n#15 0x5d95bcace638 <unknown>\n#16 0x5d95bcace810 <unknown>\n#17 0x5d95bcadddac <unknown>\n#18 0x7cb85b29ca94 <unknown>\n#19 0x7cb85b329c3c <unknown>", "trace": "self = <tests.test_password_recovery.TestPasswordRecovery object at 0x79ec143c7f80>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3cdb87fef1e5e8ca61dfcc51f229b258\")>\n\n    @allure.title('Тест на ввод данных и клик на кнопку \"Восстановить\"')\n    def test_entry_email_and_click_button_recovery(self, driver):\n        recovery_page = PasswordRecoveryPage(driver)\n        recovery_page.open_forgot_password_page()\n        recovery_page.entry_field_email(email=constants.EMAIL)\n>       recovery_page.click_to_button_restore()\n\ntests/test_password_recovery.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/password_recovery_page.py:48: in click_to_button_restore\n    self.click_to_element(locator=PasswordRecoveryLocators.BUTTON_RESTORE)\npages/base_page.py:18: in click_to_element\n    self.wait.until(ec.element_to_be_clickable(locator)).click()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"3cdb87fef1e5e8ca61dfcc51f229b258\")>, method = <function element_to_be_clickable.<locals>._predicate at 0x79ec1440f1a0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5d95bcadec7a <unknown>\nE       #1 0x5d95bc7c1e2c <unknown>\nE       #2 0x5d95bc80e661 <unknown>\nE       #3 0x5d95bc80e751 <unknown>\nE       #4 0x5d95bc852f64 <unknown>\nE       #5 0x5d95bc8315ed <unknown>\nE       #6 0x5d95bc850303 <unknown>\nE       #7 0x5d95bc831363 <unknown>\nE       #8 0x5d95bc801247 <unknown>\nE       #9 0x5d95bc801b9e <unknown>\nE       #10 0x5d95bcaa524b <unknown>\nE       #11 0x5d95bcaa92f1 <unknown>\nE       #12 0x5d95bca90afe <unknown>\nE       #13 0x5d95bcaa9e52 <unknown>\nE       #14 0x5d95bca7579f <unknown>\nE       #15 0x5d95bcace638 <unknown>\nE       #16 0x5d95bcace810 <unknown>\nE       #17 0x5d95bcadddac <unknown>\nE       #18 0x7cb85b29ca94 <unknown>\nE       #19 0x7cb85b329c3c <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "start": 1723499107218, "stop": 1723499117902, "uuid": "b6464459-43ea-401a-9e9b-f40a3f5423f9", "historyId": "28e293ff0b0ad518d95ac1f7c18fb562", "testCaseId": "28e293ff0b0ad518d95ac1f7c18fb562", "fullName": "tests.test_password_recovery.TestPasswordRecovery#test_entry_email_and_click_button_recovery", "labels": [{"name": "epic", "value": "Группа тестов на Восстановление пароля"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_password_recovery"}, {"name": "subSuite", "value": "TestPasswordRecovery"}, {"name": "host", "value": "oleg-BOM-WXX9"}, {"name": "thread", "value": "75294-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_password_recovery"}]}